<a href="https://colab.research.google.com/github/AdnanAnwarR/practice_DS/blob/main/Hands_On_Day_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Langkah  1 — Perhitungan Dasar

 Peserta akan berlatih menggunakan Python untuk operasi dasar:
* Penjumlahan
* Pengurangan
* Perkalian
* Pembagian
* Pangkat
* Modulus


In [11]:
#inisialisasi
a = 8
b = 7
c=3


In [12]:
#penjumlahan
a + b

15

In [13]:
#pengurangan
a-b

1

In [14]:
#perkalian
a * b

56

In [15]:
#pembagian
a / b

1.1428571428571428

In [18]:
#pangkat
c**c

27

In [17]:
#modulus
a % b

1

# Langkah  2 — Mengenal Data Types di Python

1. Character (String)

In [19]:
mystring = "Jeruk warnanya orange"
mystring

'Jeruk warnanya orange'

In [20]:
mystring += "banget"
mystring

'Jeruk warnanya orangebanget'

2. Numeric – Integer

In [23]:
angka = 10
print(angka)
print(type(angka))

10
<class 'int'>


3. Numeric – Real/Decimal (Float)


In [24]:
floats = 49.82
print(floats)
print(type(floats))

49.82
<class 'float'>


4. Logical (Boolean)

In [25]:
benar = True
salah = False
print(benar)
print(type(benar))
print(salah)
print(type(salah))


True
<class 'bool'>
False
<class 'bool'>


5. Complex Number

In [26]:
z = 3 + 4j
print(type(z))

<class 'complex'>


# Langkah  3 — Mengenal Struktur Data Python

1. Vector

In [27]:
#list
mylist = [1, 2, 3, 4, 5, 6]
mylist

[1, 2, 3, 4, 5, 6]

In [46]:
#numpy
import numpy as np
myarray = np.array([1, 2, 3,7])
print(myarray)

[1 2 3 7]


2. List

In [34]:
list_makanan = ["ayam","ikan","burger","ikan"]
list_makanan

['ayam', 'ikan', 'burger', 'ikan']

3. Matrix

In [33]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
print(matrix)
print(matrix[2])
print(matrix[2][1])

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[7, 8, 9]
8


4. Set

In [36]:
print(list_makanan)
set_makanan = set(list_makanan)
print(set_makanan)

['ayam', 'ikan', 'burger', 'ikan']
{'ikan', 'ayam', 'burger'}


5. Tuple

In [39]:
titik_a = (3, 4)
titik_b = (-2, 5)
titik_c = (0, 0)

print(titik_a)
print(titik_b)
print(titik_c)

(3, 4)
(-2, 5)
(0, 0)


6. Dictionary

In [40]:
mahasiswa = {
    "M001": {
        "nama": "Budi Santoso",
        "umur": 20,
        "nilai": 85.5
    },
    "M002": {
        "nama": "Ani Wijaya",
        "umur": 19,
        "nilai": 92.0
    }
}

print(mahasiswa)

{'M001': {'nama': 'Budi Santoso', 'umur': 20, 'nilai': 85.5}, 'M002': {'nama': 'Ani Wijaya', 'umur': 19, 'nilai': 92.0}}


7. Array

In [44]:
import numpy as pd
Myarray = np.array([1, 2, 3, 4])
MyList = [9,8,7,6]


In [47]:
print(myarray)
print(Myarray)
array_total = myarray + Myarray
print(array_total)

[1 2 3 7]
[1 2 3 4]
[ 2  4  6 11]


In [48]:
# Matriks 2x3
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# Matriks 3x2
B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

In [49]:
C = np.dot(A, B)
print(C)

[[ 58  64]
 [139 154]]
