<a href="https://colab.research.google.com/github/AdnanAnwarR/practice_DS/blob/main/Practice_DS_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Operator

## Aritmetik

In [ ]:
a = 7
b = 3

In [ ]:
a + b

10

In [ ]:
a - b

4

In [ ]:
# Kalau tidak pakai print, perintah terakhir saja yang muncul pada output
a + b
a - b

4

In [ ]:
print(a + b)
print(a - b)

10
4


In [ ]:
a * b

21

In [ ]:
a / b

2.3333333333333335

In [ ]:
# Operator / (bagi) selalu menghasilkan bilangan float,
# meskipun secara matematis hasil baginya bilangan bulat.
9 / 3

3.0

In [ ]:
9 / 0

ZeroDivisionError: division by zero

In [ ]:
a // b

2

In [ ]:
a ** b

343

In [ ]:
a % b

1

In [ ]:
# Bagaimana cara mengecek apakah suatu bilangan itu genap/ganjil?
a = 7
if a%2 == 0:
    print(f'{a} adalah bilangan genap')
else:
    print(f'{a} adalah bilangan ganjil')

7 adalah bilangan ganjil


In [ ]:
import math

math.floor(7/3)

2

In [ ]:
math.ceil(7/3)

3

## Penugasan

In [ ]:
mynumber = 37
mynumber

37

In [ ]:
mynumber += 5
mynumber

42

In [ ]:
myanothernumber += 8
myanothernumber

NameError: name 'myanothernumber' is not defined

In [ ]:
mystring = "Jeruk warnanya orange"
mystring

'Jeruk warnanya orange'

In [ ]:
mystring += "suffix"
mystring

'Jeruk warnanya orangesuffix'

In [ ]:
mystring = "Prefix" + mystring
mystring

'PrefixJeruk warnanya orangesuffix'

In [ ]:
mystring -= "suffix"
mystring

TypeError: unsupported operand type(s) for -=: 'str' and 'str'

## Perbandingan

In [ ]:
a = 7
b = 3
c = 9

In [ ]:
a > b

True

In [ ]:
a < b

False

In [ ]:
a != b

True

In [ ]:
a > b > c

False

In [ ]:
# True    False
a > b and b > c

False

In [ ]:
a > b < c

True

In [ ]:
# True    True
a > b and b < c

True

## Logika

In [ ]:
# False   True     True
a < b and b < c or a < c

True

In [ ]:
# False    True     True
a < b and (b < c or a < c)

False

In [ ]:
# Kalau and duluan, langkahnya seperti ini
# True or False
# True

# Kalau or duluan, langkahnya seperti ini
# True and False
# False

True or False and False

True

In [ ]:
import math

In [ ]:
math.pi

3.141592653589793

In [ ]:
f"Pi sampai 20 digit = {math.pi:.20f}"

'Pi sampai 20 digit = 3.14159265358979311600'

## Keanggotaan

In [ ]:
warna = ["merah", "jingga", "kuning", "hijau", "biru", "ungu"]

In [ ]:
"merah" in warna

True

In [ ]:
"navy" in warna

False

In [ ]:
request_warna = "teal"
if request_warna in warna:
    print("Warna tersedia.")
else:
    print("Warna belum tersedia.")

Warna belum tersedia.


# Tipe Data

## String

In [ ]:
mytext = "Air mineral murni sejuk"

In [ ]:
mytext *= "biru"

TypeError: can't multiply sequence by non-int of type 'str'

In [ ]:
mytext *= 3
mytext

'Air mineral murni sejukAir mineral murni sejukAir mineral murni sejuk'

In [ ]:
mytext /= 3

TypeError: unsupported operand type(s) for /=: 'str' and 'int'

In [ ]:
# Apakah ada kata "Air" di dalam mytext
"Air" in mytext

True

In [ ]:
"air" in mytext

False

In [ ]:
# Potong mytext berdasarkan spasi
mytext.split()

['Air',
 'mineral',
 'murni',
 'sejukAir',
 'mineral',
 'murni',
 'sejukAir',
 'mineral',
 'murni',
 'sejuk']

In [ ]:
# Potong mytext berdasarkan huruf "A"
mytext.split("A")

['',
 'ir mineral murni sejuk',
 'ir mineral murni sejuk',
 'ir mineral murni sejuk']

In [ ]:
mytext.upper()

'AIR MINERAL MURNI SEJUKAIR MINERAL MURNI SEJUKAIR MINERAL MURNI SEJUK'

In [ ]:
mytext.lower()

'air mineral murni sejukair mineral murni sejukair mineral murni sejuk'

In [ ]:
mytext.replace("sejukAir", "sejuk Air")

'Air mineral murni sejuk Air mineral murni sejuk Air mineral murni sejuk'

In [ ]:
# Cara menambahkan enter di dalam string,
# yakni dengan \n
print(mytext.replace("sejukAir", "sejuk\nAir"))

Air mineral murni sejuk
Air mineral murni sejuk
Air mineral murni sejuk


# Struktur Data

## Basic dari Python

### List

In [ ]:
mylist = [1, 2, 3, 4, 5, 6]
mylist

[1, 2, 3, 4, 5, 6]

In [ ]:
# List di dalam list
mylist = [
    [0, 0],
    [0, 1],
    [1, 1],
]
mylist

[[0, 0], [0, 1], [1, 1]]

In [ ]:
mylist = [
    "Apel",
    9,
    [3, 7],
]
mylist

['Apel', 9, [3, 7]]

In [ ]:
myfirstlist = [1, 2, 3]
mysecondlist = [6, 7, 8]
myfirstlist + mysecondlist

[1, 2, 3, 6, 7, 8]

In [ ]:
myfirstlist + [4]

[1, 2, 3, 4]

In [ ]:
myfirstlist.append(4)
myfirstlist

[1, 2, 3, 4]

### Tuple

In [ ]:
mytuple = (1, 2, 3)
mytuple

(1, 2, 3)

In [ ]:
mytuple + (4)

TypeError: can only concatenate tuple (not "int") to tuple

In [ ]:
mytuple[0]

1

In [ ]:
mytuple[0] = 4
mytuple

TypeError: 'tuple' object does not support item assignment

In [ ]:
mysecondtuple = (6, 7, 8)
mynewtuple = mytuple + mysecondtuple
mynewtuple

(1, 2, 3, 6, 7, 8)

### Range

In [ ]:
range(4)

range(0, 4)

In [ ]:
list(range(4))

[0, 1, 2, 3]

In [ ]:
list(range(7, 36, 6))

[7, 13, 19, 25, 31]

### Dict

In [ ]:
mydictionary = {
    "customer": "Anna",
    "tanggal_login": "2026-04-11",
    "produk": "Tumbler",
    "Banyak": 3,
    "Harga": 100000,
}

In [ ]:
mydictionary

{'customer': 'Anna',
 'tanggal_login': '2026-04-11',
 'produk': 'Tumbler',
 'Banyak': 3,
 'Harga': 100000}

In [ ]:
mydictionary["customer"]

'Anna'

In [ ]:
"promo" in mydictionary

False

In [ ]:
mydictionary["promo"]

KeyError: 'promo'

In [ ]:
mydictionary.get("promo")

In [ ]:
mydictionary.get("promo", "Tidak ada promo")

'Tidak ada promo'

In [ ]:
mysecondictionary = {
    "nama": "Anna",
    "nama": "Sentosa",
}
mysecondictionary

{'nama': 'Sentosa'}

In [ ]:
mysecondictionary["nama"]

'Sentosa'

### Set

In [ ]:
myset = {2, 3, 4, 5}
myset

{2, 3, 4, 5}

In [ ]:
myset = {2, 3, 4, 5, 5}
myset

{2, 3, 4, 5}

In [ ]:
myset = {5, 2, 3, 4, 5, 5}
myset

{2, 3, 4, 5}

In [ ]:
mylist = ["Aceh", "Jawa Barat", "Bali", "Jawa Barat"]
set(mylist)

{'Aceh', 'Bali', 'Jawa Barat'}

## Pakai NumPy

In [ ]:
import numpy as np

In [ ]:
mylist = [1, 2, 3]
myarray = np.array([1, 2, 3])

In [ ]:
mylist

[1, 2, 3]

In [ ]:
myarray

array([1, 2, 3])

In [ ]:
mysecondlist = [6, 7, 8]
mysecondarray = np.array([6, 7, 8])

In [ ]:
mylist + mysecondlist

[1, 2, 3, 6, 7, 8]

In [ ]:
myarray + mysecondarray

array([ 7,  9, 11])

In [ ]:
myarray * mysecondarray

array([ 6, 14, 24])

In [ ]:
np.dot(myarray, mysecondarray)

np.int64(44)

# Challenge

In [ ]:
# Bagaimana cara kita mengurutkan 2 buah string seperti di dalam kamus.
# Kita tidak tahu mana yang isinya "Gelas", mana yang isinya "Kartu".
# Misalnya, input berikut:
teks1 = "Kartu"
teks2 = "Gelas"

# Ekspektasinya terurut alfabet:
# Gelas
# Kartu

In [ ]:
if teks1 < teks2:
  print(teks1)
  print(teks2)
else:
  print(teks2)
  print(teks1)

Gelas
Kartu


In [ ]:
teks1 = "Kartu"
teks2 = "Gelas"
newString = [teks1, teks2]
newString.sort()
newString

['Gelas', 'Kartu']